# Generated by Django 4.2 on 2024-10-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_added',
            new_name='date_created',
        ),
    ]
