# Generated by Django 4.2 on 2024-10-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_order_date_order_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='description',
            new_name='additional_notes',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='colors',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='order_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='order',
            name='actual_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cycle_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='actual_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cycle_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='estimated_delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='job_order',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='micron',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='order_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='organization_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='print_product',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='submission_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
