# Generated by Django 4.2 on 2024-10-21 14:34

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_description_order_additional_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='job_order',
            field=models.CharField(default=dashboard.models.generate_job_order, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='submission_id',
            field=models.CharField(default=dashboard.models.generate_submission_id, max_length=50, null=True),
        ),
    ]
