# Generated by Django 4.2 on 2024-10-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_product_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='job_order',
            field=models.CharField(default='JO-000', max_length=50, unique=True),
        ),
    ]
