# Generated by Django 4.2 on 2024-10-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Annual', 'Annual Leave'), ('Sick', 'Sick Leave'), ('Personal', 'Personal Leave'), ('Maternity', 'Maternity Leave'), ('Paternity', 'Paternity Leave'), ('Parental', 'Parental Leave'), ('Bereavement', 'Bereavement Leave'), ('Compassionate', 'Compassionate Leave'), ('Study', 'Study/Educational Leave'), ('Sabbatical', 'Sabbatical Leave'), ('Unpaid', 'Unpaid Leave'), ('Jury Duty', 'Jury Duty Leave'), ('Military', 'Military Leave'), ('Public Service', 'Public Service Leave'), ('Religious', 'Religious Leave'), ('Casual', 'Casual Leave'), ('Compensatory', 'Compensatory Leave'), ('Medical', 'Medical/Mental Health Leave'), ('Marriage', 'Marriage Leave'), ('Voting', 'Voting Leave'), ('Emergency', 'Emergency Leave'), ('Other', 'Other')], max_length=20),
        ),
    ]
