# Generated by Django 4.2 on 2024-10-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
