# Generated by Django 4.2 on 2024-10-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_productstatushistory_delete_productionstatushistory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_created'], 'permissions': [('can_approve_jobs', 'Can approve job orders'), ('can_view_all_jobs', 'Can view all job orders'), ('can_export_jobs', 'Can export job orders'), ('can_manage_production', 'Can manage production status'), ('view_dashboard', 'Can view dashboard'), ('manage_leave', 'Can manage leave requests'), ('can_export_products', 'Can export products'), ('can_export_leaves', 'Can export leaves')]},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Electronics', 'Electronics'), ('Food', 'Food'), ('BOPP', 'BOPP')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
