# Generated by Django 4.2 on 2024-11-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_loan_options_alter_loan_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['status'], name='dashboard_l_status_4628c6_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['applied_date'], name='dashboard_l_applied_de5c73_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['user'], name='dashboard_l_user_id_68130d_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='dashboard_l_status_d0912c_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['applied_date'], name='dashboard_l_applied_4d7cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user'], name='dashboard_l_user_id_15e3db_idx'),
        ),
    ]
